# Generated by Django 5.0.1 on 2024-10-07 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageproduct',
            name='name',
        ),
    ]
