# Generated by Django 5.0.1 on 2024-10-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_orderitem_selected_image_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('pending-2', 'Chờ xác nhận'), ('processing', 'Đang Xử Lý'), ('shipping', 'Đang Giao Hàng'), ('delivered', 'Đã Nhận'), ('cancelled', 'Đã Hủy'), ('returned', 'Hoàn Trả')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Quản Trị Viên'), ('customer', 'Khách Hàng')], default='customer', max_length=10),
        ),
    ]
