# Generated by Django 5.0.1 on 2024-10-07 09:18

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_rename_product_id_imageproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='selected_image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
